title: x-stats
description: "An attempt to becoming an x-pert in football data analytics"
author: Ushnik Mukherjee
email: mukherjee.ushnik@gmail.com
url: "https://u3mukher.github.io/x-stats/"
theme: minima
minima:
  skin: solarized
  social_links:
    github: u3mukher

timezone: America/Toronto
lang: en

markdown: kramdown
highlighter: rouge

# Remove or comment out nav_links if it was there:
# nav_links:
#   - title: Blog
#     url: /blog/
#   - title: About
#     url: /about/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/

github:
  is_project_page: true
