# Site settings
title: x-stats
description: "An attempt to becoming an x-pert in football data analytics"
author: Ushnik Mukherjee
email: mukherjee.ushnik@gmail.com
url: "https://u3mukher.github.io/x-stats/" # Update this with your GitHub Pages URL

# Theme and appearance
theme: minima
minima:
  skin: solarized
  social_links:
    github: u3mukher

# SEO and analytics (optional)
timezone: America/Toronto
lang: en

# Markdown and content settings
markdown: kramdown
highlighter: rouge

# Remove nav_links to avoid minima default nav
# nav_links:
#   - title: Blog
#     url: /blog/
#   - title: About
#     url: /about/

# Additional plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Exclusions (optional)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/

github:
  is_project_page: true
